
import jsPDF from "jspdf";

export function generateComplianceReport(fileName, biasResults, geminiResults) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const addLine = (text, size = 11, bold = false, color = [30, 30, 30]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, pageWidth - 40);
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, 20, y);
      y += size * 0.5 + 2;
    });
    y += 2;
  };

  const addDivider = () => {
    doc.setDrawColor(220, 220, 220);
    doc.line(20, y, pageWidth - 20, y);
    y += 8;
  };

  const addBadge = (text, x, yPos, bgColor, textColor) => {
    doc.setFillColor(...bgColor);
    doc.roundedRect(x, yPos - 5, text.length * 2.8 + 8, 8, 2, 2, "F");
    doc.setTextColor(...textColor);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(text, x + 4, yPos);
  };

  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("FairSight", 20, 18);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("AI Bias Audit Report", 20, 28);
  doc.text("Generated: " + new Date().toLocaleDateString("en-IN"), 20, 36);
  y = 55;

  addLine("Dataset: " + fileName, 11, true);
  addLine("Analysis Date: " + new Date().toLocaleString("en-IN"), 10, false, [100, 100, 100]);
  y += 4;
  addDivider();

  addLine("Executive Summary", 14, true, [30, 30, 30]);
  y += 2;

  const score = biasResults.fairnessScore;
  const scoreColor = score >= 80 ? [22, 163, 74] : score >= 60 ? [217, 119, 6] : [220, 38, 38];
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...scoreColor);
  doc.text(String(score), 20, y + 10);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("/ 100 Fairness Score", 38, y + 10);
  const statusText = score >= 80 ? "PASS - Low Risk" : score >= 60 ? "MODERATE RISK" : "FAIL - High Risk";
  addBadge(statusText, 20, y + 22, scoreColor, [255, 255, 255]);
  y += 36;

  if (geminiResults && geminiResults.summary) {
    addLine(geminiResults.summary, 10, false, [60, 60, 60]);
  } else {
    addLine(biasResults.rawSummary, 10, false, [60, 60, 60]);
  }
  y += 4;
  addDivider();

  addLine("Detailed Findings by Group", 14, true);
  y += 2;

  biasResults.groupResults.forEach(g => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(g.group + " (" + g.column + ")", 20, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text("Approval rate: " + g.approvalRate + "%  |  Records: " + g.count + "  |  Disparity: " + g.disparity + "%", 20, y + 6);
    const riskColor = g.riskLevel === "high" ? [220, 38, 38] : g.riskLevel === "medium" ? [217, 119, 6] : [22, 163, 74];
    const riskText = g.riskLevel === "high" ? "HIGH BIAS" : g.riskLevel === "medium" ? "MEDIUM" : "FAIR";
    addBadge(riskText, pageWidth - 45, y + 2, riskColor, [255, 255, 255]);
    y += 16;
  });

  y += 4;
  addDivider();

  if (biasResults.intersectionalFlags.length > 0) {
    addLine("Intersectional Bias", 14, true);
    y += 2;
    biasResults.intersectionalFlags.forEach(f => {
      if (y > 260) { doc.addPage(); y = 20; }
      addLine(f.groups, 10, true, [220, 38, 38]);
      addLine("Approval rate: " + f.approvalRate + "% vs baseline " + f.baseRate + "% — " + f.disparity + "% disparity", 10, false, [80, 80, 80]);
      y += 2;
    });
    addDivider();
  }

  if (geminiResults && geminiResults.recommendations) {
    addLine("Recommended Fixes", 14, true);
    y += 2;
    geminiResults.recommendations.forEach((r, i) => {
      if (y > 250) { doc.addPage(); y = 20; }
      addLine((i + 1) + ". " + r.title, 11, true, [30, 30, 30]);
      addLine(r.explanation, 10, false, [80, 80, 80]);
      addLine("Estimated improvement: +" + r.estimatedImprovement + "%  |  Difficulty: " + r.difficulty, 9, false, [120, 120, 120]);
      y += 4;
    });
    addDivider();
  }

  if (geminiResults && geminiResults.regulatoryRisk) {
    addLine("Regulatory Risk", 14, true, [220, 38, 38]);
    y += 2;
    addLine(geminiResults.regulatoryRisk, 10, false, [80, 80, 80]);
    addDivider();
  }

  addLine("About This Report", 11, true, [100, 100, 100]);
  addLine("Generated by FairSight — AI Bias Detection Platform", 9, false, [150, 150, 150]);
  addLine("Built for Solution Challenge 2026 India — Unbiased AI Decision track", 9, false, [150, 150, 150]);
  addLine("All CSV processing is done locally in the browser. No data is sent to any server.", 9, false, [150, 150, 150]);

  const safeFileName = fileName.replace(".csv", "").replace(/[^a-z0-9]/gi, "-");
  doc.save("fairsight-audit-" + safeFileName + "-" + Date.now() + ".pdf");
}